# Data
path: C:/Users/AHMED/Desktop/labeled_data/labeled_data
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Keypoints
kpt_shape: [24, 3]  # [number of keypoints, number of dim]


# Classes
names:
  0: cheetass
